[project]
name = "indic-voice"
version = "0.1.0"
description = "Decoder-Only Neural TTS with Native G2P for Indian Languages"
authors = [
  {name = "Kushal Kant Bind", email = "bindkushalkant@gmail.com"}
]
readme = "README.md"
license = {text = "Apache-2.0"}
requires-python = ">=3.9"
dependencies = [
  "torch>=2.0",
  "soundfile",
  "numpy",
  "huggingface_hub",
  "loguru",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatchling.build.targets.wheel]
packages = ["indicvoice"]
